# Generated by Django 3.1.6 on 2021-02-19 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='massage',
            new_name='message',
        ),
    ]
